# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7575a9bfbcb8c3445153cfa265e843f2ecb9564f9e5c027d4ae65606026492f9e61736d50fffc4617da7c3217ba1a2de5500980f2f25750ff81828fad07aec0

test:
  secret_key_base: ea4659afbe9f29099f5c7066416fdbcaf1acad914939aa669f7b595ac02b5e583222c1a84b19008bc4e5ad423cb3f958933c619109d2c0be4af081c43ab4b982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
